export const n: string;
export const s: string;
export const e: string;
export const ne: string;
export const nw: string;
export const se: string;
export const sw: string;
export const w: string;
export const inner: string;
