export const Cropper: string;
export const img: string;
export const clone: string;
export const frame: string;
export const source: string;
export const modal: string;
export const move: string;
export const uncropped: string;
export const cropping: string;
